### ISSUE TITLE
License file not found

### ISSUE THREAD

**Issue by KevinLikesDringCoffe** [cvxgrp/cvxpygen#52]
I was trying to run the example/main.py but came across this error. How can I fix it?

`UserWarning: conda builds of osqp are built on shared libraries; by the design of osqp, these have a different Application Binary Interface (ABI) than those required for codegen, and this is therefore not supported.
  warn(
Traceback (most recent call last):
  File "/vol/datastore/zhenyu/opt/cvxpygen/examples/main.py", line 31, in <module>
    cpg.generate_code(problem, code_dir='nonneg_LS')
  File "/home/zhenyu/miniconda3/lib/python3.10/site-packages/cvxpygen/cpg.py", line 78, in generate_code
    solver_interface.generate_code(code_dir, solver_code_dir, cvxpygen_directory, parameter_canon)
  File "/home/zhenyu/miniconda3/lib/python3.10/site-packages/cvxpygen/solvers.py", line 305, in generate_code
    shutil.copyfile(os.path.join(cvxpygen_directory, 'solvers', 'osqp-python', 'LICENSE'),
  File "/home/zhenyu/miniconda3/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'nonneg_LS/c/solver_code/LICENSE'`

**Comment by maxschaller** [comment]
This is related to your `osqp` installation. Please use a pip build of osqp for now: `pip install osqp`

**Comment by KevinLikesDringCoffe** [comment]
I have already installed the OSQP. And this problem still happened even I used another solver.
