### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gibor1992** [cvxgrp/cvxpygen#55]
Hi i'm trying to compile the following example with Visual Studio Code either with Pyton 3.9.9 either 3.11.1:

```
# =============================================================================
import cvxpy as cp

# define dimensions
H, n, m = 10, 6, 3

# define variables
U = cp.Variable((m, H), name='U')
X = cp.Variable((n, H+1), name='X')

# define parameters
Psqrt = cp.Parameter((n, n), name='Psqrt')
Qsqrt = cp.Parameter((n, n), name='Qsqrt')
Rsqrt = cp.Parameter((m, m), name='Rsqrt')
A = cp.Parameter((n, n), name='A')
B = cp.Parameter((n, m), name='B')
x_init = cp.Parameter(n, name='x_init')

# define objective
objective = cp.Minimize(cp.sum_squares(Psqrt@X[:,H]) + cp.sum_squares(Qsqrt@X[:,:H]) + cp.sum_squares(Rsqrt@U))

# define constraints
constraints = [X[:,1:] == A@X[:,:H]+B@U,
               cp.abs(U) <= 1,
               X[:,0] == x_init]

# define problem
problem = cp.Problem(objective, constraints)

from cvxpygen import cpg
cpg.generate_code(problem, code_dir='MPC_code')
# =============================================================================
```

Always the compilation end with the following results:

```
=============================================================================
PS D:\users\f47594c> & "C:/Program Files/Python311/python.exe" d:/MPC_CVXPYGEN.py
Generating code with CVXPYgen ...
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 222, constraints m = 252
          nnz(P) + nnz(A) = 1434
settings: linear system solver = qdldl,
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off, time_limit: off

Getting workspace from OSQP object...                           [done]
Creating target directories...                                  [done]
Copying OSQP sources...                                         [done]
Generating customized code...                                   [done]
Creating project...
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ProgramData/MATLAB/SupportPackages/R2018b/3P.instrset/mingw_w64.instrset/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/ProgramData/MATLAB/SupportPackages/R2018b/3P.instrset/mingw_w64.instrset/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- We are on a Windows system
-- Embedded is 2 -DDFLOAT:BOOL=OFF -DDLONG:BOOL=ON
-- Passing EMBEDDED flag to compiler
-- Disabling printing for embedded
-- Printing is OFF
-- Disabling profiling for embedded
-- Profiling is OFF
-- Floats are OFF
-- Long integers (64bit) are ON
-- Configuring done
-- Generating done
-- Build files have been written to: D:/users/f47594c/MPC_code/c/solver_code/build
[done]
Compiling Python wrapper...                                     emosqpmodule.c
C:\Program Files\Python311\include\pyconfig.h(59): fatal error C1083: Non è possibile aprire il file inclusione: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
[done]
Copying code-generated Python solver to current directory...    Traceback (most recent call last):
  File "d:\MPC_CVXPYGEN.py", line 86, in <module>
    cpg.generate_code(problem, code_dir='MPC_code')
  File "D:\users\f47594c\AppData\Roaming\Python\Python311\site-packages\cvxpygen\cpg.py", line 79, in generate_code
    solver_interface.generate_code(code_dir, solver_code_dir, cvxpygen_directory, parameter_canon)
  File "D:\users\f47594c\AppData\Roaming\Python\Python311\site-packages\cvxpygen\solvers.py", line 301, in generate_code
    osqp_obj.codegen(os.path.join(code_dir, 'c', 'solver_code'), project_type=cmake_generator,
  File "D:\users\f47594c\AppData\Roaming\Python\Python311\site-packages\osqp\interface.py", line 313, in codegen
    cg.codegen(work, folder, python_ext_name, project_type, compile_python_ext,
  File "D:\users\f47594c\AppData\Roaming\Python\Python311\site-packages\osqp\codegen\code_generator.py", line 181, in codegen
    raise ValueError('No Python module generated! ' +
ValueError: No Python module generated! Some errors have occurred.
=============================================================================

```
Can you help me ? Did anyone already face this problem?
Thanks you, 
Giulio

**Comment by maxschaller** [comment]
It looks like this is an issue with your Python installation. While trying to compile the `osqp` module, the error message says that the file `C:\Program Files\Python311\include\pyconfig.h` cannot include `io.h`, which is unrelated to `osqp` (or `cvxpygen`). I suggest to install Python 3.9 and `cvxpygen` into a fresh virtual environment and retry.

Feel free to re-open the issue if the error persists.
